CREATE TABLE Person (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name varchar(100) NOT NULL,
        email varchar(100) UNIQUE NOT NULL,
        birth_year int NOT NULL CHECK ( birth_year > 1900 AND birth_year <= EXTRACT(year FROM now()))
);

INSERT INTO Person (full_name, birth_year, email)
VALUES ('Petrenko Oleksiy', 1970, 'cv@gmail.com'),
       ('Sivkovich Jane', 2003, 'jane@gmail.com'),
       ('Johnny Cash', 1999, 'test@ukr.net'),
       ('Zinchenko Maxim Pavlovich', 1983, 'zinch@ukr.net'),
       ('Ivanov Ivan Borisovich', 1998, 'ds@gmail.com'),
       ('Alekseenko Nastya', 1989, 'alekseyenko@ukr.net');

CREATE TABLE Book (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title varchar(100) NOT NULL,
        author varchar(100) NOT NULL,
        book_year INT NOT NULL CHECK ( year > 1400 AND year <= EXTRACT(year FROM now())),
        person_id int REFERENCES Person(id) ON DELETE SET NULL,
        taken_at TIMESTAMP
);

INSERT INTO Book (title, author, book_year)
VALUES ('Tiger hunters', 'Ivan Bagryany', 1946),
       ('Kobzar', 'Taras Shevchenko ', 1840),
       ('Animal Farm', 'George Orwell', 1945),
       ('On the road', 'Jack Kerouac', 1951),
       ('Roughing It ', 'Mark Twain', 1872),
       ('Gethsemane Garden', 'Ivan Bagryany', 1950),
       ('Thinking in Java', 'Bruce Eckel ', 1988);